version: 2.0.{build}
configuration: Release

image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

before_build:
  - cmd: dotnet restore

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
  
test:
  assemblies: '**\*.Tests.dll'

deploy: off